function(event, funcs) {
    var INPUT_METER_HZ = 10;
    var INPUT_METER_INTERVAL_MS = Math.round(1000 / INPUT_METER_HZ);

    var inputMeter = event.icon.find('.pluckometer-input-meter')[0];
    var cvMeter = event.icon.find('.pluckometer-cv-meter')[0];
    var cvPendingValue = null;
    var cvLastPaintMs = 0;
    var cvMeterTimer = null;
    var onsetLed = event.icon.find('.pluckometer-onset-led')[0];
    var smileCurve = event.icon.find('.pluckometer-smile-curve')[0];
    var silenceThresholdDb = (inputMeter && typeof inputMeter._silenceThresholdDb === 'number')
        ? inputMeter._silenceThresholdDb
        : -90.0;
    if (!inputMeter && !cvMeter && !onsetLed && !smileCurve) {
        return;
    }

    var inputMask = inputMeter ? inputMeter.querySelector('.pluckometer-input-meter-mask') : null;
    var cvMask = cvMeter ? cvMeter.querySelector('.pluckometer-cv-meter-mask') : null;
    if (!inputMask && !cvMask && !onsetLed) {
        return;
    }

    function flushInputPaint() {
        if (!inputMeter || !inputMask) {
            return;
        }
        var db = (typeof inputMeter._pendingInputDb === 'number') ? inputMeter._pendingInputDb : -90.0;
        if (db < -90.0) db = -90.0;
        if (db > 0.0) db = 0.0;
        var norm = (db + 90.0) / 90.0;
        if (norm < 0.0) norm = 0.0;
        if (norm > 1.0) norm = 1.0;
        inputMask.style.height = ((1 - norm) * 100) + '%';
        paintInputThreshold();
        inputMeter._lastInputPaintMs = Date.now();
        inputMeter._inputMeterTimer = null;
    }

    function queueInputPaint(db) {
        if (!inputMeter) {
            return;
        }
        inputMeter._pendingInputDb = db;
        var now = Date.now();
        var last = inputMeter._lastInputPaintMs || 0;
        var elapsed = now - last;
        if (elapsed >= INPUT_METER_INTERVAL_MS) {
            flushInputPaint();
            return;
        }
        if (!inputMeter._inputMeterTimer) {
            inputMeter._inputMeterTimer = setTimeout(flushInputPaint, INPUT_METER_INTERVAL_MS - elapsed);
        }
    }

    function paintInputThreshold() {
        // Optionally, implement a threshold marker overlay for the mask version if needed.
        // For now, this is a no-op or could set a CSS variable for a marker.
    }

    function paintSmile(cv) {
        if (!smileCurve) {
            return;
        }

        // Interpolate from a flat line (cv=0) to a smiling curve (cv=1).
        var t = cv;
        if (t < 0.0) t = 0.0;
        if (t > 1.0) t = 1.0;

        var startY = 25 - (15 * t);
        var endY = startY;
        var controlY = 25 + (20 * t);
        smileCurve.setAttribute('d', 'M 10 ' + startY + ' Q 50 ' + controlY + ' 90 ' + endY);
    }

    function flushCvPaint() {
        if (!cvMask) return;
        var cv = (typeof cvPendingValue === 'number') ? cvPendingValue : 0.0;
        if (cv < 0.0) cv = 0.0;
        if (cv > 1.0) cv = 1.0;
        cvMask.style.height = ((1 - cv) * 100) + '%';
        paintSmile(cv);
        cvLastPaintMs = Date.now();
        cvMeterTimer = null;
    }

    function queueCvPaint(cv) {
        if (!cvMask) return;
        cvPendingValue = cv;
        var now = Date.now();
        var elapsed = now - cvLastPaintMs;
        if (elapsed >= INPUT_METER_INTERVAL_MS) {
            flushCvPaint();
            return;
        }
        if (!cvMeterTimer) {
            cvMeterTimer = setTimeout(flushCvPaint, INPUT_METER_INTERVAL_MS - elapsed);
        }
    }

    if (event.type === 'start') {
        var hiddenSliderSymbols = ['onset_method', 'onset_sensitivity', 'window_seconds', 'leaky_mix', 'leaky_decay_seconds', 'cv_smoothing', 'offset_cv_out', 'scale_cv_out'];
        for (var s = 0; s < hiddenSliderSymbols.length; s++) {
            var hiddenSlider = event.icon.find('.mod-slider-image[mod-port-symbol="' + hiddenSliderSymbols[s] + '"]').closest('.mod-slider');
            if (hiddenSlider && hiddenSlider.length) {
                hiddenSlider.addClass('pluckometer-hidden-control');
            }
        }

        // Hide only the autogenerated control-group silence slider.
        // Keep the dedicated custom silence slider visible.
        var autoSilenceSlider = event.icon.find('.mod-control-group .mod-slider-image[mod-port-symbol="silence_threshold"]').closest('.mod-slider');
        if (autoSilenceSlider && autoSilenceSlider.length) {
            autoSilenceSlider.addClass('pluckometer-hidden-control');
        }

        if (inputMeter && inputMeter._inputMeterTimer) {
            clearTimeout(inputMeter._inputMeterTimer);
            inputMeter._inputMeterTimer = null;
        }

        if (inputMask) {
            inputMask.style.height = '100%';
        }
        if (cvMask) {
            cvMask.style.height = '100%';
            cvPendingValue = 0.0;
            cvLastPaintMs = Date.now();
            if (cvMeterTimer) {
                clearTimeout(cvMeterTimer);
                cvMeterTimer = null;
            }
        }
        if (onsetLed) onsetLed.classList.remove('active');
        paintInputThreshold();
        paintSmile(0.0);
        return;
    }

    var symbol = event.symbol || (event.port && event.port.symbol);
    var value = (typeof event.value !== 'undefined') ? event.value : (event.port && event.port.value);
    var numericValue = parseFloat(value);
    if (!isFinite(numericValue)) {
        return;
    }

    if (symbol === 'input_level_db') {
        var db = numericValue;
        queueInputPaint(db);
        return;
    }

    if (symbol === 'silence_threshold') {
        silenceThresholdDb = numericValue;
        if (inputMeter) {
            inputMeter._silenceThresholdDb = silenceThresholdDb;
        }
        paintInputThreshold();
        return;
    }

    if (symbol === 'cv_out_meter') {
        queueCvPaint(numericValue);
        return;
    }

    if (symbol === 'onset_indicator') {
        if (onsetLed) {
            onsetLed.classList.toggle('active', numericValue > 0.5);
        }
    }
}
